language: node_js
node_js:
    # fails on nodejs 0.10 because there is no "new Set()"
    #- "0.10"

    # fails because mocha's "SyntaxError: Use of const in strict mode."
    #- "0.12"

    # disabled node 0.x for now until we find a way arround, 
    # npm tests fail on node 0.x but otherwise library is working normal

    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    - "9"
    - "10"
    # iojs merged into nodejs
    #- "iojs"

env:
  global:
    - AWS_ACCESS_KEY_ID=fakeMyKeyId
    - AWS_SECRET_ACCESS_KEY=fakeSecretAccessKey
    - AWS_REGION=us-east-1

before_script:
  - wget http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_latest.tar.gz -O /tmp/dynamodb_local_latest.tar.gz
  - tar -xzf /tmp/dynamodb_local_latest.tar.gz -C /tmp
  - java -Djava.library.path=/tmp/DynamoDBLocal_lib -jar /tmp/DynamoDBLocal.jar -inMemory &
  - sleep 2
  

addons:
  hosts:
    - dynamodb-local